# Imports and Overview

In [2]:
# Neural Network
import tensorflow as tf
from tensorflow.keras.models import Model

from tf_agents.replay_buffers import tf_uniform_replay_buffer

# Further support
import numpy as np
from tqdm.notebook import tqdm_notebook



# Environment

In [3]:
from numpy import dtype


class Buffer:
    
    def __init__(self):
        self.storage = np.empty(0)
        self.size = self.storage.size





    def save(self, data):

        # Free thousand slots in buffer
        while self.storage.size > 9000:
            self.storage = np.delete(self.storage, -1)


        self.storage = np.append(self.storage, data)
        self.storage = np.reshape(self.storage, (-1, 3))


        #return self.storage[0]

    def sample(self):
        return(tf.convert_to_tensor(self.storage[random.randint(0, self.size)], dtype=float))

    def lol(self):
        print(self.storage[0])
    

# Experience Replay Buffer

In [5]:
# Has to save (Observation, action, reward, terminal state)
from numpy import float32


class Buffer:

    def __init__(
        self,
        batch_size=50,
        buffer_length=1000, 
        observation_size=192*48,
        action_size=2
    ):
        '''
        Create replay buffer

        Buffer size = batch_size * buffer_length

        '''
        # Save batch size for other functions of buffer
        self.batch_size = batch_size

        # Tell buffer what data & which size to expect
        self.data_spec = (
            tf.TensorSpec(
                shape=[1, observation_size],
                dtype=tf.dtypes.float32,
                name="Observation"
            ),
            tf.TensorSpec(
                shape=[1, action_size],
                dtype=tf.dtypes.int32,
                name="Action"
            ),
            tf.TensorSpec(
                # Reward size
                shape=[1, 1],
                dtype=tf.dtypes.float32,
                name="Reward"
            ),
            tf.TensorSpec(
                shape=[1, 1],
                # Either 0 or 1 
                dtype=tf.dtypes.bool,
                name="Terminal State"
            )
        )

        # Create the buffer 
        self.buffer = tf_uniform_replay_buffer.TFUniformReplayBuffer(
            self.data_spec, batch_size, buffer_length
        )

    def stupid(self):
        return self.data_spec

    def add(self, items):
        '''
        length of items must be equal to batch size

        items: list or tuple of batched data from (50, 4)


        '''
        # Combine all values from "items" in tensor
        # Not sure wether we need tf.nest.map_structure
        self.batched_values = tf.nest.map_structure(
            lambda t: tf.stack([t] * self.batch_size),
            items
        )

        # Add to batch
        self.buffer.add_batch(self.batched_values)

    def sample(self):
        return self.buffer.as_dataset(single_deterministic_pass=False)


buffer = Buffer(batch_size=1, observation_size=4)
# Save sizes of the stupid tensors
data_spec = buffer.stupid()

for t in range(4):
    buffer.add((
        tf.constant([1.0,2.0,3.0,4.0], shape=data_spec[0].shape.as_list()),
        tf.constant([5], shape=data_spec[1].shape.as_list()),
        tf.constant([6.0], shape=data_spec[2].shape.as_list()),
        tf.constant([True], shape=data_spec[3].shape.as_list())
    ))


dataset = buffer.sample()

iterator = iter(dataset)
print("Iterator trajectories:")
trajectories = []
for _ in range(3):
  t, _ = next(iterator)
  trajectories.append(t)

print(trajectories)

print(tf.nest.map_structure(lambda t: t.shape, trajectories))


Iterator trajectories:
[(<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[1., 2., 3., 4.]], dtype=float32)>, <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[5, 5]], dtype=int32)>, <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[6.]], dtype=float32)>, <tf.Tensor: shape=(1, 1), dtype=bool, numpy=array([[ True]])>), (<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[1., 2., 3., 4.]], dtype=float32)>, <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[5, 5]], dtype=int32)>, <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[6.]], dtype=float32)>, <tf.Tensor: shape=(1, 1), dtype=bool, numpy=array([[ True]])>), (<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[1., 2., 3., 4.]], dtype=float32)>, <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[5, 5]], dtype=int32)>, <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[6.]], dtype=float32)>, <tf.Tensor: shape=(1, 1), dtype=bool, numpy=array([[ True]])>)]
[(TensorShape([1, 4]), TensorShape([1, 2]), Tenso

# Actor Critic Agent

# World model

# World model & agent training loops

# Hyperparam inits
Agent Data collection in environment + adding data to ERB (+ measure at which reward loop stops?) \par
World model loop on data sampled from ERB \par
Agent training loop with world model feedback
 

# Function execution